### ISSUE TITLE
カードUI実装

### ISSUE THREAD

**Issue by 2814109** [2814109/md-editor#4]
以下機能を実装してほしいです
・編集状態（MDで表示）
・参照状態（HTMLで表示：プレビュー状態）
・編集後の保存

保存機能の詳細
ASIS
・編集状態
TOBE
・参照状態に変更

**Comment by 2814109** [comment]
Styleをよろしくです！

**Comment by nierNieRyorhaYoRHa** [comment]
ニューもフィズム

**Comment by 2814109** [comment]
キャンセルの動線も必要ですね！
